---
title: "Day 0 - Made a Promise"
author: "Shashank Hosahalli Shivamurthy"
date: 2025-06-18
format: html
description: "The beginning of \"30 Days of Hell Out There\": hopefully, a raw, personal journey of building, learning, and fighting back."
---

**“Nobody is going to look at my resume and just give me a job. There's no way! I have to stand out.”**

I said that to myself in the mirror this morning. It made me realize the truth.

Obviously, no one’s coming to save me.  
No recruiter is going to slide into my inbox. Or will they? No clue 
And definitely I am not some god coder.

But I am just a guy who still wants to fight.

---

## The Promise

So I said to myself that for the next 30 days, I am going to show up no matter what.

**30 days. No excuses. Just show up.**

Every single day, I said I will:
- Learn something hard
- Build something real
- Write about it
- Share the journey

Just showing up every. single. day.

---

## Why did I call it “30 Days of Hell Out There”?

Because honestly, it feels like hell right now. Very uncertain. Feeling lost

- Not knowing where I stand  
- Feeling like I am falling behind  
- Waking up anxious  

This blog — this whole series — is me swinging back.

Just wanted to document everything.

---

## Inspired by the KING

It’s inspired by **Virat Kohli** — not just for the records, but for the mindset.

- Ruthless discipline  
- Showing up when no one’s watching  
- Grinding when it’s hard  
- And proving yourself over and over again

That’s what I’m trying to tap into.

---

## This is Day 0

No fake positivity.  
No “I’ve got this” energy.  
Just real. Just effort.

Just me, showing up.  

Let’s see where this goes.



> PS: I am going to try to keep it as raw as possible just my initial thoughts and not focusing on the actual quality of the formatting.
I used GPT for this day 0, but going forward, hopefully raw. Thanks for reading! Let's get it!
